window.PORTFOLIO_PROJECT_SEED = [
  {
    slug: 'xpenso',
    title: 'Xpenso',
    category: 'web',
    categories: ['web', 'software'],
    year: '',
    role: 'Finance tracking app',
    thumbnail_url: 'assets/projects/xpenso/thumbnail.png',
    screenshot_urls: [
      'assets/projects/xpenso/landing.jpeg',
      'assets/projects/xpenso/dashboard.jpeg',
      'assets/projects/xpenso/Budgetcategories.jpeg',
      'assets/projects/xpenso/income streams.jpeg',
      'assets/projects/xpenso/settings.jpeg',
      'assets/projects/xpenso/smart alerts.jpeg',
      'assets/projects/xpenso/visual reports.jpeg',
      'assets/projects/xpenso/456.png'
    ],
    description_html: '<p>A polished expense and budget manager built around clear financial visibility, quick tracking, and actionable insights.</p>',
    tech_stack: ['JavaScript', 'UI Design', 'Charts', 'Budgeting'],
    live_url: null,
    github_url: null,
    featured: true,
    sort_order: 1
  },
  {
    slug: 'bingo',
    title: 'Bingo',
    category: 'web',
    categories: ['web', 'software'],
    year: '',
    role: 'Multiplayer game',
    thumbnail_url: 'assets/projects/bingo/thumbnail.jpg',
    screenshot_urls: [
      'assets/projects/bingo/landing.jpg',
      'assets/projects/bingo/setupgrid.jpg',
      'assets/projects/bingo/waiting room.jpg',
      'assets/projects/bingo/gameroom.jpg',
      'assets/projects/bingo/gameplay.jpg',
      'assets/projects/bingo/rematch.jpg',
      'assets/projects/bingo/gameover.jpg'
    ],
    description_html: '<p>A fast, social bingo experience with game-room flow, multiplayer setup, and replay-friendly states.</p>',
    tech_stack: ['JavaScript', 'Realtime UX', 'Game UI'],
    live_url: null,
    github_url: null,
    featured: true,
    sort_order: 2
  },
  {
    slug: 'finpath',
    title: 'FinPath',
    category: 'web',
    categories: ['web'],
    year: '',
    role: 'Finance planning app',
    thumbnail_url: 'assets/projects/finpath/1.png',
    screenshot_urls: ['assets/projects/finpath/1.png'],
    description_html: '<p>A finance planning companion focused on helping users map goals, track progress, and stay organized.</p>',
    tech_stack: ['JavaScript', 'Finance UX'],
    live_url: null,
    github_url: null,
    featured: true,
    sort_order: 3
  },
  {
    slug: 'flofin',
    title: 'FloFin',
    category: 'web',
    categories: ['web'],
    year: '',
    role: 'Finance dashboard',
    thumbnail_url: 'assets/projects/flofin/1.png',
    screenshot_urls: ['assets/projects/flofin/1.png'],
    description_html: '<p>A streamlined finance dashboard for tracking money flow, balances, and everyday planning.</p>',
    tech_stack: ['JavaScript', 'Dashboard UI'],
    live_url: null,
    github_url: null,
    featured: true,
    sort_order: 4
  },
  {
    slug: 'geminiwatermarkremover',
    title: 'Gemini Watermark Remover',
    category: 'software',
    categories: ['software', 'web'],
    year: '',
    role: 'AI image utility',
    thumbnail_url: 'assets/projects/geminiwatermarkremover/1.png',
    screenshot_urls: ['assets/projects/geminiwatermarkremover/1.png'],
    description_html: '<p>An AI-assisted image utility with a clean interface for previewing and refining visual content.</p>',
    tech_stack: ['AI Tools', 'Image Processing'],
    live_url: null,
    github_url: null,
    featured: true,
    sort_order: 5
  },
  {
    slug: 'fitlife',
    title: 'FitLife',
    category: 'web',
    categories: ['web'],
    year: '',
    role: 'Fitness tracker',
    thumbnail_url: 'assets/projects/fitlife/1.png',
    screenshot_urls: ['assets/projects/fitlife/1.png'],
    description_html: '<p>A health and fitness experience centered on habits, movement, and daily progress tracking.</p>',
    tech_stack: ['JavaScript', 'Wellness UX'],
    live_url: null,
    github_url: null,
    featured: false,
    sort_order: 6
  },
  {
    slug: 'clg-comp',
    title: 'College Companion',
    category: 'web',
    categories: ['web'],
    year: '',
    role: 'Campus app',
    thumbnail_url: 'assets/projects/clg-comp/1.png',
    screenshot_urls: [
      'assets/projects/clg-comp/1.png',
      'assets/projects/clg-comp/2.png',
      'assets/projects/clg-comp/3.png',
      'assets/projects/clg-comp/4.png',
      'assets/projects/clg-comp/5.png',
      'assets/projects/clg-comp/6.png',
      'assets/projects/clg-comp/7.png'
    ],
    description_html: '<p>A campus-focused companion app concept for student workflows, updates, and everyday organization.</p>',
    tech_stack: ['JavaScript', 'Campus Tools'],
    live_url: null,
    github_url: null,
    featured: false,
    sort_order: 7
  },
  {
    slug: 'ipa',
    title: 'IPA',
    category: 'web',
    categories: ['web'],
    year: '',
    role: 'Product prototype',
    thumbnail_url: 'assets/projects/ipa/1.png',
    screenshot_urls: ['assets/projects/ipa/1.png'],
    description_html: '<p>A compact prototype that highlights interface polish, structure, and responsive presentation.</p>',
    tech_stack: ['JavaScript', 'Prototype UI'],
    live_url: null,
    github_url: null,
    featured: false,
    sort_order: 8
  },
  {
    slug: 'resume',
    title: 'Resume Showcase',
    category: 'design',
    categories: ['design', 'web'],
    year: '',
    role: 'Portfolio resume preview',
    thumbnail_url: 'assets/projects/resume/1.png',
    screenshot_urls: ['assets/projects/resume/1.png'],
    description_html: '<p>A resume presentation built to support a strong personal brand and easy sharing.</p>',
    tech_stack: ['Layout Design', 'Presentation'],
    live_url: null,
    github_url: null,
    featured: false,
    sort_order: 9
  }
];